package memory

import (
	"errors"
	"strings"
	"time"
)

// Sentinel errors reported by the workspace-scoped memory boundary.
var (
	ErrWorkspaceRequired = errors.New("memory: workspace id is required")
	ErrInvalidLayer      = errors.New("memory: invalid layer")
	ErrInvalidKey        = errors.New("memory: invalid key")
	ErrSecretRejected    = errors.New("memory: secret-shaped content is not stored")
	ErrValueTooLarge     = errors.New("memory: value exceeds the maximum size")
	ErrInvalidTTL        = errors.New("memory: invalid ttl")
	ErrRateLimited       = errors.New("memory: write rate limit exceeded")
	ErrNotFound          = errors.New("memory: not found")
)

// Bounds enforced at the facade boundary (abuse controls, ROADMAP §8).
const (
	// MaxKeyLength, MaxValueBytes and MaxTTL are the bounds shared by the
	// domain and every transport boundary. Keeping them exported prevents an
	// HTTP adapter from inventing a looser limit than the Redis facade.
	MaxKeyLength  = 256
	MaxValueBytes = 64 * 1024
	MaxTTL        = 90 * time.Hour // 90 days upper bound
	DefaultTTL    = 24 * time.Hour

	maxKeyLength  = MaxKeyLength
	maxValueBytes = MaxValueBytes
	maxTTL        = MaxTTL
)

// ValidLayer reports whether l is a recognized memory layer.
func ValidLayer(l MemoryLayer) bool {
	switch l {
	case LayerSession, LayerLongTerm, LayerWorkspace, LayerOrganizational:
		return true
	}
	return false
}

// layerString returns the partition segment for a layer.
func layerString(l MemoryLayer) string {
	switch l {
	case LayerSession:
		return "session"
	case LayerLongTerm:
		return "longterm"
	case LayerWorkspace:
		return "workspace"
	case LayerOrganizational:
		return "org"
	}
	return "unknown"
}

// validateKey rejects blank/oversized keys and keys that would collide with a
// partition or another namespace (partition-prefix confusion, P15 minimal
// disclosure). It returns ErrInvalidKey when the key is unusable.
func validateKey(key string) error {
	trimmed := strings.TrimSpace(key)
	if trimmed == "" || trimmed != key {
		return ErrInvalidKey
	}
	if len(key) > maxKeyLength {
		return ErrInvalidKey
	}
	if strings.ContainsAny(key, "\x00\r\n/") {
		return ErrInvalidKey
	}
	// Reject already-partitioned names so callers cannot smuggle a second
	// workspace/org namespace into the cell key and create collisions with
	// keys generated by partitionKey.
	if strings.HasPrefix(key, "workspace:") || strings.HasPrefix(key, "org:") {
		return ErrInvalidKey
	}
	return nil
}
